[package]
name = "feetech-servo-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
serialport = "4.7.0"
thiserror = "2.0.12"

[dev-dependencies]
ctrlc = "3.4.5"                 # For teleoperate example
