name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install libudev
      run: sudo apt-get update && sudo apt-get install -y libudev-dev
    - name: Build
      run: cargo build --verbose --all-targets
    - name: Run tests
      run: cargo test --verbose --all-targets
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
